version: '3.4'

services:
  web:
    build:
      context: personal-website
      target: builder
    ports:
      - 8080:80
    # volumes:
    #   - ./personal-website:/project
    #   - /project/node_modules